---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install required packages
  apt: "name={{ item }} state=present"
  with_items:
    - make

- name: Create working directory
  file:
    path: /usr/src
    state: directory

- name: Download ruby-install
  get_url:
    url: https://github.com/postmodern/ruby-install/archive/v{{ ruby_install_version }}.tar.gz
    dest: /usr/src/ruby-install-{{ ruby_install_version }}.tar.gz
  when:
    ansible_local is not defined or
    ansible_local.ruby_install is not defined or
    ansible_local.ruby_install.version != ruby_install_version
  register: ruby_install_downloaded

- name: Extract ruby-install
  shell: tar -C /usr/src -xzvf /usr/src/ruby-install-{{ ruby_install_version }}.tar.gz
  when: ruby_install_downloaded | changed

- name: Install ruby-install
  become: true
  shell:
    chdir=/usr/src/ruby-install-{{ ruby_install_version }}
    make install
  when: ruby_install_downloaded | changed
  register: ruby_install_installed

- name: Clean up ruby-install sources
  shell: rm -rf /usr/src/ruby-install-*
  when: ruby_install_downloaded | changed

#
# Setup ruby-install facts.d
#
- name: Capture installed ruby-install version
  shell: ruby-install --version | awk '{ print $2 }'
  ignore_errors: yes
  register: installed_ruby_install_version
  changed_when: False

- name: Create ansible facts directory
  become: true
  file: state=directory recurse=yes path=/etc/ansible/facts.d

- name: Set ruby-install facts
  become: true
  template: src=ruby_install.fact dest=/etc/ansible/facts.d/ruby_install.fact
